version: '3.5'
services:
  search_api:
    container_name: 'search_api'
    build: ./search-api
    ports:
      - '8080:8080'
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'elasticsearch:5.6.8'
    command: elasticsearch
    expose:
      - '9200'
      - '9300'
